import logging
import os
from github import Github
from pydantic import BaseModel

import config
import github_client
import llm_client
from analysis import diff_for_model

logger = logging.getLogger(__name__)

TEST_GENERATOR_PROMPT = """You are MergeMaster AI's Autonomous Test Engineer.
Your job is to analyze the PR diff and write a production-ready, high-quality unit test file.

Guidelines:
1. Determine the appropriate test framework from the file extension (e.g., PyTest for Python, Vitest/Jest for TS/JS).
2. Propose a sensible new test file path (e.g., `tests/test_<name>.py` or `src/__tests__/<name>.test.ts`).
3. Write comprehensive tests covering:
   - Happy paths and expected behavior
   - Edge cases (null/undefined/empty inputs, boundary values)
   - Error handling and expected exceptions
4. Provide a 1-2 sentence explanation of the test coverage.

Return a JSON object matching this schema:
{
  "test_file_path": "path/to/test_file.ext",
  "framework": "pytest | vitest | jest",
  "test_code": "full code of the test file",
  "explanation": "brief description of test scenarios"
}
Respond with JSON only."""


class GeneratedTestSuite(BaseModel):
    test_file_path: str
    framework: str
    test_code: str
    explanation: str


async def generate_tests(
    pr_title: str,
    diff: str,
    files: list[str],
) -> GeneratedTestSuite | None:
    """Generate comprehensive unit tests based on the PR diff."""
    if not (config.LLM_API_BASE and config.GEMINI_API_KEY):
        # Fallback template if no LLM key
        sample_file = files[0] if files else "module"
        ext = os.path.splitext(sample_file)[1].lower()
        if ext in (".py",):
            test_path = f"tests/test_{os.path.splitext(os.path.basename(sample_file))[0]}.py"
            code = (
                f"# Automated Test generated by MergeMaster AI for {sample_file}\n"
                f"import pytest\n\n"
                f"def test_{os.path.splitext(os.path.basename(sample_file))[0]}_basic():\n"
                f"    \"\"\"Verify basic execution and constraints for {pr_title}.\"\"\"\n"
                f"    assert True\n"
            )
            framework = "pytest"
        else:
            test_path = f"tests/{os.path.splitext(os.path.basename(sample_file))[0]}.test.ts"
            code = (
                f"// Automated Test generated by MergeMaster AI for {sample_file}\n"
                f"import {{ describe, it, expect }} from 'vitest'\n\n"
                f"describe('{pr_title}', () => {{\n"
                f"  it('should execute without errors', () => {{\n"
                f"    expect(true).toBe(true)\n"
                f"  }})\n"
                f"}})\n"
            )
            framework = "vitest"
        return GeneratedTestSuite(
            test_file_path=test_path,
            framework=framework,
            test_code=code,
            explanation="Heuristic placeholder test suite generated without active LLM key.",
        )

    user_prompt = (
        f"PR Title: {pr_title}\n"
        f"Touched Files: {', '.join(files[:10])}\n\n"
        f"{diff_for_model(diff)}"
    )

    try:
        content = await llm_client.chat_completions(
            system=TEST_GENERATOR_PROMPT,
            user=user_prompt,
            temperature=0.2,
        )
        return GeneratedTestSuite.model_validate_json(content)
    except Exception as exc:
        logger.warning("unit test generation failed: %s", exc)
        return None


def push_test_commit(
    repo_name: str,
    head_ref: str,
    test_file_path: str,
    test_code: str,
    github_token: str | None = None,
) -> tuple[str | None, str]:
    """Push the generated unit test file as a commit to the PR branch."""
    _, repo = github_client.get_authenticated_repo(repo_name, github_token)
    if not repo:
        return None, "No valid GitHub App credentials or user token available."

    try:

        # Check if file already exists on the branch
        sha = None
        try:
            contents = repo.get_contents(test_file_path, ref=head_ref)
            if not isinstance(contents, list):
                sha = contents.sha
        except Exception:
            sha = None

        if sha:
            res = repo.update_file(
                path=test_file_path,
                message=f"[MergeMaster] Tests: update unit tests in {test_file_path}",
                content=test_code,
                sha=sha,
                branch=head_ref,
            )
        else:
            res = repo.create_file(
                path=test_file_path,
                message=f"[MergeMaster] Tests: add autonomous unit tests in {test_file_path}",
                content=test_code,
                branch=head_ref,
            )

        commit_sha = res["commit"].sha
        logger.info("pushed test commit %s for %s", commit_sha[:7], test_file_path)
        return commit_sha, f"Unit test file `{test_file_path}` successfully committed ({commit_sha[:7]})."
    except Exception as exc:
        logger.warning("failed to push test file: %s", exc)
        return None, f"Failed to push test commit: {exc}"
