/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardPoliciesRouteImport } from './routes/_dashboard.policies'
import { Route as DashboardRepositoriesIndexRouteImport } from './routes/_dashboard.repositories.index'
import { Route as DashboardRepositoryIdRouteImport } from './routes/_dashboard.repository.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepositoriesIndexRoute =
  DashboardRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRepositoryIdRoute = DashboardRepositoryIdRouteImport.update({
  id: '/repository/$id',
  path: '/repository/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/policies': typeof DashboardPoliciesRoute
  '/repository/$id': typeof DashboardRepositoryIdRoute
  '/repositories/': typeof DashboardRepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/anotherPage': typeof AnotherPageRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/policies': typeof DashboardPoliciesRoute
  '/': typeof DashboardIndexRoute
  '/repository/$id': typeof DashboardRepositoryIdRoute
  '/repositories': typeof DashboardRepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/anotherPage': typeof AnotherPageRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/policies': typeof DashboardPoliciesRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/repository/$id': typeof DashboardRepositoryIdRoute
  '/_dashboard/repositories/': typeof DashboardRepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/callback'
    | '/login'
    | '/analytics'
    | '/policies'
    | '/repository/$id'
    | '/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anotherPage'
    | '/callback'
    | '/login'
    | '/analytics'
    | '/policies'
    | '/'
    | '/repository/$id'
    | '/repositories'
  id:
    | '__root__'
    | '/_dashboard'
    | '/anotherPage'
    | '/callback'
    | '/login'
    | '/_dashboard/analytics'
    | '/_dashboard/policies'
    | '/_dashboard/'
    | '/_dashboard/repository/$id'
    | '/_dashboard/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AnotherPageRoute: typeof AnotherPageRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/policies': {
      id: '/_dashboard/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/repositories/': {
      id: '/_dashboard/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof DashboardRepositoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/repository/$id': {
      id: '/_dashboard/repository/$id'
      path: '/repository/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof DashboardRepositoryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRepositoryIdRoute: typeof DashboardRepositoryIdRoute
  DashboardRepositoriesIndexRoute: typeof DashboardRepositoriesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRepositoryIdRoute: DashboardRepositoryIdRoute,
  DashboardRepositoriesIndexRoute: DashboardRepositoriesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AnotherPageRoute: AnotherPageRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
